[package]
name = "devnetfaucet"
version = "0.0.0"
edition = "2018"
publish = false
authors = [ "you",]

[lib]
path = "src/swap.rs"

[dependencies.elrond-wasm]
version = "0.30.0"

[dev-dependencies.elrond-wasm-debug]
version = "0.30.0"
